package vo;

// Generated 2013-1-16 15:17:33 by Hibernate Tools 3.4.0.CR1

import java.util.*;

import net.tsz.afinal.annotation.sqlite.Id;

import android.R.integer;
import android.content.Context;

/**
 * CouponClass generated by hbm2java
 */
public class CouponsFamily {
	@Id
	public String id;

	public String couponname;

	public String state;

	public String couponstips;
	public String coupondetail;

	public String commentsum;

	public String accountnum;

	public String getCouponstips() {
		return couponstips;
	}

	public void setCouponstips(String couponstips) {
		this.couponstips = couponstips;
	}

	public String getCreateuser() {
		return createuser;
	}

	public void setCreateuser(String createuser) {
		this.createuser = createuser;
	}

	public String getValiditybegin() {
		return validitybegin;
	}

	public void setValiditybegin(String validitybegin) {
		this.validitybegin = validitybegin;
	}

	public String getValidityend() {
		return validityend;
	}

	public void setValidityend(String validityend) {
		this.validityend = validityend;
	}

	public String getValiditydays() {
		return validitydays;
	}

	public void setValiditydays(String validitydays) {
		this.validitydays = validitydays;
	}

	public String accountreserved;

	public String photonum;

	public String imageurl;
	public String createuser;
	public String validitybegin;
	public String validityend;
	public String validitydays;

	public String getAccountnum() {
		return accountnum;
	}

	public String getAccountreserved() {
		return accountreserved;
	}

	public String getCommentsum() {
		return commentsum;
	}

	public String getCoupondetail() {
		return coupondetail;
	}

	public String getCouponname() {
		return couponname;
	}

	public String getId() {
		return id;
	}

	public String getImageurl() {
		return imageurl;
	}

	public String getPhotonum() {
		return photonum;
	}

	public String getState() {
		return state;
	}

	public void setAccountnum(String accountnum) {
		this.accountnum = accountnum;
	}

	public void setAccountreserved(String accountreserved) {
		this.accountreserved = accountreserved;
	}

	public void setCommentsum(String commentsum) {
		this.commentsum = commentsum;
	}

	public void setCoupondetail(String coupondetail) {
		this.coupondetail = coupondetail;
	}

	public void setCouponname(String couponname) {
		this.couponname = couponname;
	}

	public void setId(String id) {
		this.id = id;
	}

	public void setImageurl(String imageurl) {
		this.imageurl = imageurl;
	}

	public void setPhotonum(String photonum) {
		this.photonum = photonum;
	}

	public void setState(String state) {
		this.state = state;
	}

}
